version: '3'
services:
  frontend:
    build:
      context: .
    image: xue_frontend
    ports:
      - "80:80"  # Expose local port 3000 to docker port 80 where Nginx is hosting ReactApp
    volumes:
          - .:/app
    environment:
      - REACT_APP_API_URL=http://xue-xinwen.com:5000

  backend:
    build:
      context: ./backend
    image: xue_backend
    ports:
      - "5000:5000"  # Expose the Flask backend on port 5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production  # Set the Flask environment
