version: '3'
services:
  frontend:
    build:
      context: .
    image: xue_frontend
    ports:
      - "80:80"  # port 3000 for development and 80 for production
    volumes:
          - .:/app
          # Mount Nginx configuration
          #- ./nginx.conf.development:/etc/nginx/conf.d/default.conf  # for development
          - ./nginx.conf.production:/etc/nginx/conf.d/default.conf  # production
    environment:
      - PRODUCTION=true # can be true or false

  backend:
    build:
      context: ./backend
    image: xue_backend
    ports:
      - "5000:5000"  # Expose the Flask backend on port 5000
    volumes:
      - ./backend:/app
    environment:
      - PRODUCTION=true

  news_fetcher:
    build:
      context: ./backend/fetch_news
    image: xue_fetch_news
    volumes:
      - ./backend/:/app
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    restart: always
