version: '3'
services:
  frontend:
    build:
      context: .
    image: xue_frontend
    ports:
      - "3000:80"  # Expose local port 3000 to docker port 80 where Nginx is hosting ReactApp
    volumes:
          - .:/app
    environment:
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - FAST_REFRESH=false
      - REACT_APP_API_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
    image: xue_backend
    ports:
      - "5000:5000"  # Expose the Flask backend on port 5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development  # Set the Flask environment (you can customize this)
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - FAST_REFRESH=false

  news_fetcher:
    build:
      context: ./backend/fetch_news
    image: xue_fetch_news
    volumes:
      - ./backend/:/app
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    restart: always

