services:
  frontend:
    build:
      context: .
    image: xue_frontend
    ports:
      - "5173:5173"  # Vite development server port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_PRODUCTION=false
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: xue_backend
    ports:
      - "5000:5000"  # FastAPI backend port
    volumes:
      - ./backend:/app
    env_file:
      - xuexinwen.env
    environment:
      - BACKEND_PRODUCTION=false
    depends_on:
      mysql:
        condition: service_healthy
    command: python main.py

  mysql:
    image: mysql:8.0
    env_file:
      - xuexinwen.env
    volumes:
      - ./backend/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # MySQL port for development
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
