version: '3'
services:
  frontend:
    build:
      context: .
    image: xue_frontend
    ports:
      - "3000:80"  # port 3000 for development and 80 for production
    volumes:
          - .:/app
    environment:
      - PRODUCTION=false

  backend:
    build:
      context: ./backend
    image: xue_backend
    ports:
      - "5000:5000"  # Expose the Flask backend on port 5000
    volumes:
      - ./backend:/app
    environment:
      - PRODUCTION=false
